from typing import Protocol, List, Dict, Any

class MarketDataProvider(Protocol):
    async def get_candles(self, symbol: str, timeframe: str, limit: int) -> List[Dict[str, Any]]: ...
    async def get_trades(self, symbol: str, limit: int) -> List[Dict[str, Any]]: ...
    async def get_order_book(self, symbol: str, depth: int) -> Dict[str, Any]: ...
    async def subscribe_trades(self, symbol: str): ...
    async def subscribe_order_book(self, symbol: str): ...
