import { Activity, ArrowDownRight, ArrowUpRight, Wifi } from 'lucide-react';
import type { Signal } from '../api';
import { formatPrice } from '../lib/format';

export function SignalOverview({ signal, symbol, timeframe, livePrice, orderBook }: { signal: Signal | null; symbol: string; timeframe: string; livePrice?: { price: number; event_time: number } | null; orderBook?: { best_bid: number | null; best_ask: number | null; spread: number | null; mid_price: number | null } | null }) {
  const signalClass = signal?.signal.toLowerCase() || 'watch';
  const currentPrice = livePrice?.price ?? signal?.price ?? null;
  return <section className="overview-grid"><div className={`signal-card ${signalClass}`}><div className="card-label">Model signal <span className="model-pill">{signal?.model_type || 'logistic'}</span></div><div className="signal-row"><span className="signal-word">{signal?.signal || 'WATCH'}</span>{signal?.signal === 'BUY' ? <ArrowUpRight size={34} /> : signal?.signal === 'SELL' ? <ArrowDownRight size={34} /> : <Activity size={30} />}</div><div className="signal-detail">{signal?.model_available ? `${((signal.probability || 0) * 100).toFixed(1)}% model confidence` : 'Model not trained for this market yet'}</div></div><div className="price-card"><div className="card-label">Last price</div><strong>{currentPrice ? `${formatPrice(currentPrice)} USDT` : '--'}</strong><span className="muted">{symbol} · {timeframe}</span><span className="muted">{orderBook && orderBook.best_bid && orderBook.best_ask ? `Bid ${formatPrice(orderBook.best_bid)} · Ask ${formatPrice(orderBook.best_ask)}` : 'Waiting for order book'}</span></div><div className="price-card"><div className="card-label">Market state</div><strong className="state"><Wifi size={17} /> Connected</strong><span className="muted">Binance public market data</span>{orderBook && orderBook.spread !== null ? <span className="muted">Spread {formatPrice(orderBook.spread)} · Mid {formatPrice(orderBook.mid_price ?? 0)}</span> : <span className="muted">Auto refresh every 5s</span>}</div></section>;
}
