try:
    from prometheus_client import Counter, start_http_server
except ImportError:  # Local unit tests may run without the optional metrics package.
    class Counter:
        def __init__(self, *args, **kwargs):
            pass

        def labels(self, **kwargs):
            return self

        def inc(self):
            pass

    def start_http_server(port: int):
        raise RuntimeError("prometheus_client is not installed")
import threading

# Counters exported for Prometheus
trades_ingested = Counter(
    'trades_ingested_total', 'Total number of trades ingested', ['symbol']
)
orderbook_snapshots_ingested = Counter(
    'orderbook_snapshots_ingested_total', 'Total number of orderbook snapshots persisted', ['symbol']
)
websocket_reconnects = Counter(
    'websocket_reconnects_total', 'Number of websocket reconnect attempts'
)
signals_generated = Counter('signals_generated_total', 'Signals generated by direction and state', ['direction', 'state'])
quality_rejections = Counter('market_data_quality_rejections_total', 'Market data records rejected by quality validation', ['source'])
news_items_enriched = Counter('news_items_enriched_total', 'News items enriched with deterministic metadata', ['source'])
llm_validations = Counter('llm_validations_total', 'Context validations returned by configured AI provider', ['provider', 'decision'])
paper_trades = Counter('paper_trades_total', 'Virtual paper trades opened or closed', ['action', 'direction'])


def _start_server(port: int = 8001):
    start_http_server(port)


def start_metrics_server(port: int = 8001):
    t = threading.Thread(target=_start_server, args=(port,), daemon=True)
    t.start()


def inc_trade(symbol: str):
    try:
        trades_ingested.labels(symbol=symbol).inc()
    except Exception:
        pass


def inc_snapshot(symbol: str):
    try:
        orderbook_snapshots_ingested.labels(symbol=symbol).inc()
    except Exception:
        pass


def inc_ws_reconnect():
    try:
        websocket_reconnects.inc()
    except Exception:
        pass


def inc_signal(direction: str, state: str):
    try:
        signals_generated.labels(direction=direction, state=state).inc()
    except Exception:
        pass


def inc_quality_rejection(source: str):
    try:
        quality_rejections.labels(source=source).inc()
    except Exception:
        pass


def inc_news_enriched(source: str):
    try:
        news_items_enriched.labels(source=source).inc()
    except Exception:
        pass


def inc_llm_validation(provider: str, decision: str):
    try:
        llm_validations.labels(provider=provider, decision=decision).inc()
    except Exception:
        pass


def inc_paper_trade(action: str, direction: str):
    try:
        paper_trades.labels(action=action, direction=direction).inc()
    except Exception:
        pass
