import { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, Database, RefreshCw } from 'lucide-react';
import { getRegistry, type ModelVersion } from '../api';
import { PageFrame, DashboardSkeleton, NoticeStack, type Notice } from '../components';

export function ModelsScreen({ token, session, onLogout }: { token: string; session: { sub: string; role: string }; onLogout: () => void }) {
  const [models, setModels] = useState<ModelVersion[]>([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<Notice | null>(null);
  async function load() { setLoading(true); try { setModels((await getRegistry(token)).models); } catch (error) { setNotice({ type: 'error', title: 'Registry indisponível', message: error instanceof Error ? error.message : 'Não foi possível carregar versões.' }); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [token]);
  return <PageFrame session={session} onLogout={onLogout} eyebrow="Research / model registry" title="Model registry" description="Acompanhe candidatos, versões ativas e métricas de aprovação."><NoticeStack notices={notice ? [notice] : []} onDismiss={() => setNotice(null)} /><div className="page-actions"><div className="registry-summary"><Database size={18} /><span>{models.length} versões registradas</span></div><button className="button-secondary" onClick={load} disabled={loading}><RefreshCw size={15} /> Refresh</button></div>{loading ? <DashboardSkeleton /> : models.length === 0 ? <div className="empty-state panel"><Clock3 size={26} /><h2>Nenhuma versão registrada</h2><p>O retrainer criará candidatos na próxima execução.</p></div> : <div className="registry-list">{models.map((model) => <article className="registry-row panel" key={`${model.symbol}-${model.timeframe}-${model.version}`}><div className="registry-main"><span className={`status-dot ${model.active ? 'active' : ''}`} /><div><strong>{model.symbol} · {model.timeframe}</strong><span>{model.model_type} · {new Date(model.created_at).toLocaleString('pt-BR')}</span></div></div><div className="registry-metric"><span>Test AUC</span><strong>{model.metrics.test_auc?.toFixed(3) || '--'}</strong></div><div className={`version-status ${model.active ? 'approved' : 'candidate'}`}>{model.active ? <CheckCircle2 size={14} /> : <Clock3 size={14} />}{model.active ? 'Active' : 'Candidate'}</div><code>{model.version}</code></article>)}</div>}</PageFrame>;
}
