import { useEffect, useState } from 'react';
import { Activity, RefreshCw, ShieldCheck } from 'lucide-react';
import { getMultiTimeframe, getOpportunities, type MultiTimeframe, type Opportunity } from '../api';
import { PageFrame, NoticeStack, type Notice } from '../components';

const formatQuotePrice = (value: number) => value.toLocaleString('pt-BR', { minimumFractionDigits: value < 1 ? 4 : 2, maximumFractionDigits: value < 1 ? 8 : 2 });

export function OpportunitiesScreen({ token, session, onLogout }: { token: string; session: { sub: string; role: string }; onLogout: () => void }) {
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [market, setMarket] = useState<MultiTimeframe | null>(null);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState<Notice | null>(null);
  const [feeBps, setFeeBps] = useState('10');
  const [slippageBps, setSlippageBps] = useState('5');
  const [minimumProfitPct, setMinimumProfitPct] = useState('0');

  async function load() {
    setLoading(true);
    try {
      const [ranked, multiTimeframe] = await Promise.all([
        getOpportunities(token, Number(feeBps), Number(slippageBps), Number(minimumProfitPct) / 100),
        getMultiTimeframe(token, 'BTCUSDT'),
      ]);
      setOpportunities(ranked.opportunities);
      setMarket(multiTimeframe);
      setNotice(null);
    } catch (error) {
      setNotice({ type: 'error', title: 'Opportunities indisponível', message: error instanceof Error ? error.message : 'Não foi possível carregar a análise.' });
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void load(); }, [token]);

  return <PageFrame session={session} onLogout={onLogout} eyebrow="Research / opportunity scanner" title="Opportunities" description="Ranking das 20 moedas monitoradas, baseado nos modelos aprovados, risco quantitativo e contexto de mercado. Nenhuma entrada é executada automaticamente.">
    <NoticeStack notices={notice ? [notice] : []} onDismiss={() => setNotice(null)} />
    <div className="opportunity-settings panel"><div><div className="card-label">Filtro de viabilidade</div><strong>Custos e lucro mínimo esperado</strong><span>Exibe apenas alvos que cobrem custos e atingem o percentual líquido escolhido.</span></div><div className="opportunity-settings-fields"><label>Taxa (bps)<input type="number" min="0" max="1000" step="0.1" value={feeBps} onChange={(event) => setFeeBps(event.target.value)} /></label><label>Slippage (bps)<input type="number" min="0" max="1000" step="0.1" value={slippageBps} onChange={(event) => setSlippageBps(event.target.value)} /></label><label>Lucro líquido mínimo (%)<input type="number" min="0" max="1000" step="0.1" value={minimumProfitPct} onChange={(event) => setMinimumProfitPct(event.target.value)} /></label><button className="button-secondary" onClick={() => void load()} disabled={loading}><RefreshCw size={15} className={loading ? 'spin' : ''} /> Recalcular</button></div></div>
    <div className="page-actions"><div className="registry-summary"><Activity size={15} /> {opportunities.length} oportunidades com edge</div><span className="opportunity-cost-summary">Lucro líquido mínimo: {Number(minimumProfitPct).toFixed(1)}%</span></div>
    {market && <section className="panel opportunity-context"><div className="panel-heading"><div><div className="kicker">Market alignment</div><h2>{market.symbol} · {market.regime.name ?? market.regime.regime ?? 'UNKNOWN'}</h2></div><ShieldCheck size={21} color="#55c9b5" /></div><div className="timeframe-strip">{market.timeframes.map((item) => <div className="timeframe-item" key={item.timeframe}><span>{item.timeframe}</span><strong className={item.trend === 'UP' ? 'positive' : item.trend === 'DOWN' ? 'negative' : ''}>{item.trend}</strong><small>{(item.return_pct * 100).toFixed(2)}%</small></div>)}</div></section>}
    {loading ? <div className="empty-state"><RefreshCw className="spin" size={25} /><p>Consultando modelos e dados de mercado...</p></div> : opportunities.length === 0 ? <div className="empty-state"><Activity size={28} /><h2>Nenhuma oportunidade com edge</h2><p>Os setups atuais não superaram o break-even e a margem de segurança depois dos custos estimados.</p></div> : <><div className="opportunity-heading"><div><div className="kicker">Sinais elegíveis</div><h2>Melhores planos para operar</h2></div><span>Ordenado por valor esperado</span></div><section className="opportunity-list">{opportunities.map((item, index) => <article className="panel opportunity-row" key={`${item.symbol}-${item.timeframe}`}><div className="opportunity-identity"><span className="opportunity-rank">{String(index + 1).padStart(2, '0')}</span><div><div className="card-label">{item.symbol} · {item.timeframe}</div><strong className={item.direction === 'BUY' ? 'positive' : 'negative'}>{item.trade_type}</strong><span>{item.state} · qualidade {item.opportunity_quality}</span></div></div><div className="opportunity-plan"><div><small>Entrada</small><b>{formatQuotePrice(item.entry_price)}</b></div><div><small>Stop loss</small><b className="negative">{formatQuotePrice(item.stop_loss)}</b><em>{(item.net_stop_pct * 100).toFixed(2)}%</em></div><div><small>Take profit</small><b className="positive">{formatQuotePrice(item.take_profit)}</b><em>líquido {(item.net_target_pct * 100).toFixed(2)}%</em></div></div><div className="opportunity-metric"><small>Prob. direcional</small><b>{(item.directional_probability * 100).toFixed(1)}%</b><em>mínimo {(item.break_even_probability * 100).toFixed(1)}%</em></div><div className="opportunity-metric"><small>Viabilidade</small><b className={item.cost_viable ? 'positive' : 'negative'}>{item.cost_viable ? 'OK' : 'FRACA'}</b><em>mínimo {(item.required_move_pct * 100).toFixed(2)}%</em></div><div className="opportunity-viability"><small>Critério de aprovação</small><strong>{(item.net_target_pct * 100).toFixed(2)}% alvo líquido</strong><span>Mínimo exigido {(item.required_move_pct * 100).toFixed(2)}% · margem {((item.net_target_pct - item.required_move_pct) * 100).toFixed(2)}%</span></div><a className="button-primary opportunity-action" href={`/paper?symbol=${encodeURIComponent(item.symbol)}&direction=${item.trade_type}&entry=${item.entry_price}&stop=${item.stop_loss}&target=${item.take_profit}`}>Abrir no Paper</a><span className="opportunity-exit">Movimento mínimo seguro: {(item.required_move_pct * 100).toFixed(2)}% · saída automática: {item.exit_rule}</span></article>)}</section></>}
      {loading ? <div className="empty-state"><RefreshCw className="spin" size={25} /><p>Consultando modelos e dados de mercado...</p></div> : opportunities.length === 0 ? <div className="empty-state"><Activity size={28} /><h2>Nenhuma oportunidade com edge</h2><p>Os setups atuais não superaram o break-even e a margem de segurança depois dos custos estimados.</p></div> : <><div className="opportunity-heading"><div><div className="kicker">Sinais elegíveis</div><h2>Melhores planos para operar</h2></div><span>Ordenado por valor esperado</span></div><section className="opportunity-list">{opportunities.map((item, index) => <article className="panel opportunity-row" key={`${item.symbol}-${item.timeframe}`}><div className="opportunity-identity"><span className="opportunity-rank">{String(index + 1).padStart(2, '0')}</span><div><div className="card-label">{item.symbol} · {item.timeframe}</div><strong className={item.direction === 'BUY' ? 'positive' : 'negative'}>{item.trade_type}</strong><span>{item.state} · qualidade {item.opportunity_quality}</span></div></div><div className="opportunity-plan"><div><small>Entrada</small><b>{formatQuotePrice(item.entry_price)}</b></div><div><small>Stop loss</small><b className="negative">{formatQuotePrice(item.stop_loss)}</b><em>{(item.net_stop_pct * 100).toFixed(2)}%</em></div><div><small>Take profit</small><b className="positive">{formatQuotePrice(item.take_profit)}</b><em>líquido {(item.net_target_pct * 100).toFixed(2)}%</em></div></div><div className="opportunity-metric"><small>Prob. direcional</small><b>{(item.directional_probability * 100).toFixed(1)}%</b><em>mínimo {(item.break_even_probability * 100).toFixed(1)}%</em></div><div className="opportunity-metric"><small>Viabilidade</small><b className={item.cost_viable ? 'positive' : 'negative'}>{item.cost_viable ? 'OK' : 'FRACA'}</b><em>mínimo {(item.required_move_pct * 100).toFixed(2)}%</em></div><div className="opportunity-viability"><small>Decision Gate · {item.status}</small><strong>{item.action === 'PAPER_ENTRY' ? 'Elegível para entrada Paper' : 'Sem ação'}</strong><span>{item.reason_codes.join(' · ')}</span><span>{(item.net_target_pct * 100).toFixed(2)}% líquido ≥ {(item.required_move_pct * 100).toFixed(2)}% necessário · EV {(item.expected_value_pct * 100).toFixed(2)}%</span></div><a className="button-primary opportunity-action" href={`/paper?symbol=${item.symbol}&direction=${item.trade_type}&entry=${item.entry_price}&stop=${item.stop_loss}&target=${item.take_profit}`}>Abrir no Paper</a></article>)}</section></>}
  </PageFrame>;
}
