import { useEffect, useMemo, useState } from 'react';
import { Play, TrendingDown, TrendingUp } from 'lucide-react';
import { getRegistry, runBacktest, type BacktestResult, type ModelVersion } from '../api';
import { PageFrame, DashboardSkeleton, NoticeStack, type Notice } from '../components';

const fmtPct = (value: number) => `${(value * 100).toFixed(2)}%`;

export function StrategyScreen({ token, session, onLogout }: { token: string; session: { sub: string; role: string }; onLogout: () => void }) {
  const [symbol, setSymbol] = useState('BTCUSDT'); const [timeframe, setTimeframe] = useState('1h'); const [loading, setLoading] = useState(false); const [registryLoading, setRegistryLoading] = useState(true); const [result, setResult] = useState<BacktestResult | null>(null); const [notice, setNotice] = useState<Notice | null>(null); const [models, setModels] = useState<ModelVersion[]>([]);
  useEffect(() => { getRegistry(token).then((response) => setModels(response.models)).catch(() => setNotice({ type: 'error', title: 'Registry indisponível', message: 'Não foi possível verificar os modelos ativos.' })).finally(() => setRegistryLoading(false)); }, [token]);
  const activeModels = useMemo(() => new Set(models.filter((model) => model.active && model.model_type === 'logistic').map((model) => `${model.symbol}|${model.timeframe}`)), [models]);
  const active = activeModels.has(`${symbol}|${timeframe}`);
  useEffect(() => {
    if (registryLoading) return;
    if (active) return;
    const firstAvailable = ['1h', '4h', '1d'].find((candidate) => activeModels.has(`${symbol}|${candidate}`));
    if (firstAvailable) setTimeframe(firstAvailable);
  }, [registryLoading, active, activeModels, symbol]);
  async function execute() { if (!active) { setNotice({ type: 'info', title: 'Modelo não aprovado', message: `Não existe modelo ativo para ${symbol} em ${timeframe}. Escolha uma combinação aprovada ou aguarde o retrainer.` }); return; } setLoading(true); setNotice(null); try { setResult(await runBacktest(token, { symbol, timeframe, model_type: 'logistic', initial_cash: 10000, fee_bps: 10, slippage_bps: 5, confidence_threshold: .6 })); setNotice({ type: 'success', title: 'Backtest concluído', message: 'A simulação causal foi executada sem enviar ordens.' }); } catch (error) { setNotice({ type: 'error', title: 'Backtest não executado', message: error instanceof Error ? error.message : 'Verifique o modelo ativo.' }); } finally { setLoading(false); } }
  return <PageFrame session={session} onLogout={onLogout} eyebrow="Research / strategy lab" title="Strategy lab" description="Teste a estratégia no holdout temporal, com custos reais de operação, antes de considerar qualquer execução."><NoticeStack notices={notice ? [notice] : []} onDismiss={() => setNotice(null)} /><section className="research-controls panel"><div className="control-group"><label>Instrument</label><select value={symbol} onChange={(e) => setSymbol(e.target.value)}><option>BTCUSDT</option><option>ETHUSDT</option><option>SOLUSDT</option></select></div><div className="control-group"><label>Timeframe</label><select value={timeframe} onChange={(e) => setTimeframe(e.target.value)}><option value="1h" disabled={!activeModels.has(`${symbol}|1h`)}>1h {activeModels.has(`${symbol}|1h`) ? '· active' : '· unavailable'}</option><option value="4h" disabled={!activeModels.has(`${symbol}|4h`)}>4h {activeModels.has(`${symbol}|4h`) ? '· active' : '· unavailable'}</option><option value="1d" disabled={!activeModels.has(`${symbol}|1d`)}>1d {activeModels.has(`${symbol}|1d`) ? '· active' : '· unavailable'}</option></select></div><button className="button-primary run-button" onClick={execute} disabled={loading || registryLoading || !active}><Play size={16} /> {registryLoading ? 'Checking model' : loading ? 'Running...' : active ? 'Run backtest' : 'Model unavailable'}</button></section>{!registryLoading && !active && <div className="info-banner">Não há modelo Logistic aprovado para {symbol} / {timeframe}. O backtest permanece bloqueado para evitar resultados inválidos.</div>}{loading ? <DashboardSkeleton /> : result ? <><section className="result-hero panel"><div><div className="card-label">Net performance · {result.out_of_sample ? 'out-of-sample' : 'full history'}</div><strong className={result.total_return >= 0 ? 'positive' : 'negative'}>{fmtPct(result.total_return)}</strong><span>versus {fmtPct(result.buy_hold_return)} buy and hold · {result.bars} bars</span></div><div className="result-tag"><TrendingUp size={17} /> temporal holdout</div></section><section className="research-grid">{[['Sharpe ratio', result.sharpe_ratio.toFixed(2)], ['Max drawdown', fmtPct(result.max_drawdown)], ['Win rate', fmtPct(result.win_rate)], ['Total trades', String(result.total_trades)], ['Fees', `${result.total_fees.toFixed(2)} USDT`], ['Slippage', `${result.total_slippage.toFixed(2)} USDT`]].map(([label, value]) => <div className="metric panel" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section></> : <div className="empty-state panel"><TrendingDown size={26} /><h2>Run your first simulation</h2><p>Escolha uma combinação com modelo ativo para avaliar retorno, risco, custos e drawdown.</p></div>}</PageFrame>;
}
